spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: a2SvDbl48ZRS17a34xH8kRnEUn178ZFj
            client-secret: 0LhP2J_ueS20mJFdeVOJfZI3uWANtdKVw8aCl4Jhouc33YyRcM9Zglv6KtGEztxj
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://dev-s794ofn4.us.auth0.com/
